// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace HRSolutionDbLibrary.Core.Entities.hris.Tables;

public class ApplicationProcess
{
	public int Id { get; set; }

	public string ProcessName { get; set; }

	public bool IsActive { get; set; }

	public int SequenceOrder { get; set; }

	public DateTime CreatedDate { get; set; }

	public string CreatedBy { get; set; }

	public bool? IsShowOnWorkFlow { get; set; }

	public virtual ICollection<Candidate> Candidates { get; set; } = new List<Candidate>();
	public virtual ICollection<EmailAutomation> EmailAutomations { get; set; } = new List<EmailAutomation>();

	public virtual ICollection<JobApplicationProcess> JobApplicationProcesses { get; set; } = new List<JobApplicationProcess>();
}