// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace HRSolutionDbLibrary.Core.Entities.hris.Tables;

public class DepartmentTeam
{
	public int Id { get; set; }

	public string Name { get; set; }

	public string Alias { get; set; }

	public bool IsActive { get; set; }

	public DateTime CreatedDate { get; set; }

	public int DepartmentId { get; set; }

	public virtual Department Department { get; set; }
}