// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace HRSolutionDbLibrary.Core.Entities.hris.Tables;

public class Department
{
	public int Id { get; set; }

	public int DepartmentGroupId { get; set; }

	public string Logo { get; set; }

	public string Name { get; set; }

	public int IndustryId { get; set; }

	public string Website { get; set; }

	public int TimezoneId { get; set; }

	public int CoreServiceId { get; set; }

	public int DepartmentStatusId { get; set; }

	public bool IsActive { get; set; }

	public string CreatedBy { get; set; }

	public DateTime? CreatedDate { get; set; }

	public string Alias { get; set; }

	public virtual CoreService CoreService { get; set; }

	public virtual DepartmentGroup DepartmentGroup { get; set; }

	public virtual ICollection<DepartmentIndividual> DepartmentIndividuals { get; set; } = new List<DepartmentIndividual>();

	public virtual DepartmentStatus DepartmentStatus { get; set; }

	public virtual ICollection<DepartmentTeam> DepartmentTeams { get; set; } = new List<DepartmentTeam>();

	public virtual ICollection<EmployeeInformation> EmployeeInformations { get; set; } = new List<EmployeeInformation>();

	public virtual DepartmentIndustry Industry { get; set; }

	public virtual ICollection<JobProfile> JobProfiles { get; set; } = new List<JobProfile>();

	public virtual ICollection<TalentAcquisitionForm> TalentAcquisitionForms { get; set; } = new List<TalentAcquisitionForm>();

	public virtual DepartmentTimeZone Timezone { get; set; }


}