// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace HRSolutionDbLibrary.Core.Entities.hris.Tables;

public class DepartmentTimeZone
{
	public int Id { get; set; }

	public string Name { get; set; }

	public string Alias { get; set; }

	public string MnlOffset { get; set; }

	public string IanaTimeZoneId { get; set; }

	public DateTime? CreatedDate { get; set; }

	public bool IsActived { get; set; }

	public string CreatedBy { get; set; }

	public virtual ICollection<Department> Departments { get; set; } = new List<Department>();
}