// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using HRSolutionDbLibrary.Core.Entities.Tables;

public class Candidate
{
	public int Id { get; set; }

	public string FirstName { get; set; }

	public string LastName { get; set; }

	public string Email { get; set; }

	public string PhoneNumber { get; set; }

	public string Resume { get; set; }

	public int SourceId { get; set; }

	public int JobId { get; set; }

	public string CurrentEmploymentStatus { get; set; }

	public string NoticePeriod { get; set; }

	public string CurrentSalary { get; set; }

	public string ExpectedSalary { get; set; }

	public int ApplicationStatusId { get; set; }

	public bool IsDisqualified { get; set; }

	public bool IsActive { get; set; }

	public virtual ICollection<AssessmentCorrection> AssessmentCorrections { get; set; } = new List<AssessmentCorrection>();

	public virtual ICollection<AssessmentRemainingTimer> AssessmentRemainingTimers { get; set; } = new List<AssessmentRemainingTimer>();

	public virtual ICollection<CandidateAnswer> CandidateAnswers { get; set; } = new List<CandidateAnswer>();

	public virtual ICollection<CandidateComment> CandidateComments { get; set; } = new List<CandidateComment>();

	public virtual ICollection<CandidateCredential> CandidateCredentials { get; set; } = new List<CandidateCredential>();

	public virtual ICollection<CandidateHistory> CandidateHistories { get; set; } = new List<CandidateHistory>();

	public virtual ICollection<CandidateSnapshot> CandidateSnapshots { get; set; } = new List<CandidateSnapshot>();

	public virtual ICollection<CandidateWriteUp> CandidateWriteUps { get; set; } = new List<CandidateWriteUp>();

	public virtual JobProfile Job { get; set; }

	public virtual ICollection<JobApplicationAnswer> JobApplicationAnswers { get; set; } = new List<JobApplicationAnswer>();

	public virtual JobOfferInformation JobOfferInformation { get; set; }

	public virtual ICollection<OnboardingDocument> OnboardingDocument { get; set; } = new List<OnboardingDocument>();

	public virtual OnboardingInformationSheet OnboardingInformationSheet { get; set; }

	public virtual Source Source { get; set; }

	public virtual WorkFromHomeInformation WorkFromHomeInformation { get; set; }
}