// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
public class CandidateWriteUp
{
	public int Id { get; set; }

	public int CandidateId { get; set; }
	public string ProfileOverview { get; set; }

    public string ProfessionalBackground { get; set; }

	public string Skills { get; set; }

	public string Behavioral { get; set; }

	public string Notes { get; set; }

	public bool IsActive { get; set; }

	public string CreatedBy { get; set; }

	public DateTime CreatedDate { get; set; }

	public virtual Candidate Candidate { get; set; }
}