// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
public class CoreService
{
	public int Id { get; set; }

	public string Service { get; set; }

	public string Alias { get; set; }

	public bool IsActive { get; set; }

	public string CreatedBy { get; set; }

	public DateTime CreatedDate { get; set; }

	public virtual ICollection<Department> Departments { get; set; } = new List<Department>();
}