// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using HRSolutionDbLibrary.Core.Entities.Tables;

public class DepartmentIndividual
{
	public int Id { get; set; }

	public int DepartmentId { get; set; }

	public string Name { get; set; }

	public string Email { get; set; }

	public string Position { get; set; }

	public bool IsActive { get; set; }

	public virtual Department Department { get; set; }

	public virtual ICollection<TalentAcquisitionFormBatch> TalentAcquisitionFormBatches { get; set; } = new List<TalentAcquisitionFormBatch>();

	public virtual ICollection<TalentAcquisitionForm> TalentAcquisitionForms { get; set; } = new List<TalentAcquisitionForm>();

}