// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
public class DepartmentGroup
{
	public int Id { get; set; }

	public string GroupName { get; set; }

	public bool IsActive { get; set; }

	public virtual ICollection<Department> Departments { get; set; } = new List<Department>();
}