// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
public class EmailTemplate
{
	public int Id { get; set; }

	public string Name { get; set; }

	public string Subject { get; set; }

	public string EmailBody { get; set; }

	public bool IsActive { get; set; }

	public int EmailActionId { get; set; }
	public string Cc { get; set; }

	public string CreatedBy { get; set; }

	public DateTime? CreatedDate { get; set; }

	public virtual EmailAction EmailAction { get; set; }

	public virtual ICollection<EmailAutomation> EmailAutomations { get; set; } = new List<EmailAutomation>();
}