// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

public class EmailAutomation
{
	public int Id { get; set; }

	public int? JobId { get; set; }

	public int EmailTemplate { get; set; }

	public int? ApplicationId { get; set; }

	public bool IsActive { get; set; }

	public string CreatedBy { get; set; }

	public DateTime? CreatedDate { get; set; }

	public bool Disqualified { get; set; }

	public int? Type { get; set; }

	public virtual ApplicationProcess Application { get; set; }

	public virtual EmailTemplate EmailTemplateNavigation { get; set; }

	public virtual JobProfile Job { get; set; }

}