// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
public class JobApplicationProcess
{
	public int Id { get; set; }

	public int ApplicationProcessId { get; set; }

	public int JobId { get; set; }

	public bool IsActive { get; set; }

	public virtual ApplicationProcess ApplicationProcess { get; set; }

	public virtual JobProfile Job { get; set; }
}