// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
public class JobApplicationAnswer
{
	public int Id { get; set; }

	public int CandidateId { get; set; }

	public int ApplicationQuestionId { get; set; }

	public string Answer { get; set; }

	public virtual JobApplicationQuestion ApplicationQuestion { get; set; }

	public virtual Candidate Candidate { get; set; }
}