// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using HRSolutionDbLibrary.Core.Entities.Tables;

public class JobProfile
{
	public int Id { get; set; }

	public int DepartmentId { get; set; }

	public string Position { get; set; }

	public int EmploymentTypeId { get; set; }

	public int JobStatusId { get; set; }

	public string JobDescription { get; set; }

	public string Education { get; set; }

	public string Experience { get; set; }

	public string KeyResponsibility { get; set; }

	public string Qualifications { get; set; }

	public bool IsActive { get; set; }

	public bool ShowInCareerPage { get; set; }

	public string CreatedBy { get; set; }

	public DateTime CreatedDate { get; set; }

	public virtual ICollection<Candidate> Candidates { get; set; } = new List<Candidate>();

	public virtual Department Department { get; set; }

	public virtual ICollection<EmailAutomation> EmailAutomations { get; set; } = new List<EmailAutomation>();

	public virtual EmploymentType EmploymentType { get; set; }

	public virtual ICollection<JobApplicationProcess> JobApplicationProcesses { get; set; } = new List<JobApplicationProcess>();

	public virtual ICollection<JobApplicationQuestion> JobApplicationQuestions { get; set; } = new List<JobApplicationQuestion>();

	public virtual ICollection<JobAssessment> JobAssessments { get; set; } = new List<JobAssessment>();

	public virtual JobStatus JobStatus { get; set; }

	public virtual ICollection<TalentAcquisitionForm> TalentAcquisitionForms { get; set; } = new List<TalentAcquisitionForm>();
}