// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
public class JobStatus
{
	public int Id { get; set; }

	public string Status { get; set; }

	public bool IsActive { get; set; }

	public string CreatedBy { get; set; }

	public DateTime CreatedDate { get; set; }

	public virtual ICollection<JobProfile> JobProfiles { get; set; } = new List<JobProfile>();
}