// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
public class OnboardingStatus
    {
	public int Id { get; set; }

	public string StatusName { get; set; }

	public string CreatedBy { get; set; }

	public DateTime? CreatedDate { get; set; }

	public bool IsActive { get; set; }
	public virtual OnboardingInformationSheet OnboardingInformationSheet { get; set; }
}
