// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using HRSolutionDbLibrary.Core.Entities.Tables;

public class TalentAcquisitionForm
{
	public int Id { get; set; }
	public int DepartmentId { get; set; }

	public int JobId { get; set; }

	public DateTime RequestDate { get; set; }

	public int StatusId { get; set; }

	public int ReasonId { get; set; }

	public int Headcount { get; set; }

	public string Negotiable { get; set; }

	public string NonNegotiable { get; set; }

	public string Schedule { get; set; }

	public int HiringManager { get; set; }

	public string InterviewSchedule { get; set; }

	public int WorkArrangement { get; set; }

	public DateTime TargetStartDate { get; set; }

	public string TargetSalaryRange { get; set; }

	public string Equipment { get; set; }

	public string Notes { get; set; }

	public string CreatedBy { get; set; }

	public DateTime CreatedDate { get; set; }

	public int? TafBatchId { get; set; }
	public virtual Department Department { get; set; }

	public virtual DepartmentIndividual HiringManagerNavigation { get; set; }

	public virtual JobProfile Job { get; set; }

	public virtual TalentAcquisitionReason Reason { get; set; }

	public virtual TalentAcquisitionStatus Status { get; set; }

	public virtual TalentAcquisitionFormBatch TafBatch { get; set; }

	public virtual WorkArrangement WorkArrangementDetail { get; set; }

}